services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.4.2.31
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./tmp/clickhouse-data:/opt/clickhouse/data
    networks:
      - default
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

networks:
  default:
